a = input('Digite algo: ')
print('O tipo primitivo é', type(a))
print('Só tem espaço:', a.isspace())
print('É um número:', a.isnumeric())
print('É alfabético:', a.isalpha())
print('É alfanúmerico:', a.isalnum())
print('É maiúscula:', a.isupper())
print('É minúscula:', a.islower())
print('É capitalizada', a.istitle()) 
